version: '3.8'

services:
  search-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: search-engine
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - REDIS_URI=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - search-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - search-network

  redis:
    image: redislabs/redisearch:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - search-network

  mongodb-test:
    build:
      context: .
      dockerfile: Dockerfile.test.mongo
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      
  content-storage-test:
    build:
      context: .
      dockerfile: Dockerfile.test.content-storage
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - REDIS_URI=redis://redis:6379

networks:
  search-network:
    driver: bridge

volumes:
  mongodb_data: 
  redis_data: