// Professional sample supplied for UI review. Unknown credentials/testimonials are
// explicitly labelled synthetic and remain hidden. No real contact secrets are used.
const date=(year,month=0)=>({calendar:'persian',year,month,day:0});
const item=(id,fields)=>({id,visibility:'PUBLIC',...fields});
module.exports={
 header:{name:'هاتف رستمخانی',title:'مهندس DevOps و پلتفرم',tagline:'طراحی زیرساخت ابری و خودکارسازی استقرار برای تیم‌های توسعه',company:'QuickHands Inc. | پروژهٔ هاتف',location:'تهران، ایران',availabilityStatus:'AVAILABLE',bio:'بیش از ۱۵ سال تجربه در فناوری اطلاعات، برنامه‌نویسی و زیرساخت. روی طراحی پلتفرم‌های ابری، خودکارسازی استقرار و ساخت سرویس‌های پایدار کار می‌کنم. هدف من کمک به تیم‌ها برای ارائهٔ سریع‌تر و مطمئن‌تر محصول است.'},
 sections:{
  skills:['Kubernetes','Docker','AWS','Terraform','Linux','GitLab CI/CD','Prometheus','Grafana'].map((name,i)=>item('demo-skill-'+i,{name,category:i===2?'زیرساخت ابری':i>5?'مانیتورینگ':'زیرساخت و ابزارها',proficiencyLevel:'ADVANCED',isCurrentlyUsing:true,description:['طراحی و نگهداری بستر اجرای سرویس‌های کانتینری.','بسته‌بندی سرویس‌ها برای استقرار تکرارپذیر.','کار با ECS، Fargate، CloudFormation و پایش سرویس‌ها.','تعریف و مدیریت زیرساخت به‌صورت کد.','راه‌اندازی و نگهداری سرویس‌های لینوکسی.','خودکارسازی مراحل ساخت، تست و انتشار سرویس‌ها.','جمع‌آوری متریک‌ها و تعریف هشدار برای سرویس‌ها.','ساخت داشبورد برای مشاهدهٔ وضعیت سرویس‌ها.'][i]})),
  experiences:[
   item('demo-exp-quickhands',{roleTitle:'کارشناس DevOps',organizationName:'QuickHands Inc.',employmentType:'CONTRACT',locationType:'REMOTE',location:'دورکاری',startDate:date(1403,12),isCurrent:true,summary:'طراحی و مدیریت زیرساخت ابری و خودکارسازی مسیر توسعه تا استقرار.',responsibilities:['راه‌اندازی سرویس‌های کانتینری روی Amazon ECS با Fargate و Spot','پیاده‌سازی CI/CD برای ۴ پروژهٔ فرانت‌اند و ۲ بک‌اند Django','استقرار Sentry با CloudFormation و مدیریت Aurora PostgreSQL','مدیریت IAM، Secrets Manager و پایش سرویس‌ها با CloudWatch'],achievements:['خودکارسازی استقرار و کاهش کارهای تکراری تیم توسعه','بهبود مشاهده‌پذیری و تشخیص خطاهای سرویس‌ها'],technologies:['AWS ECS','Fargate','CloudFormation','Aurora PostgreSQL','GitHub Actions','Sentry'],skillIds:['demo-skill-1','demo-skill-2']}),
   item('demo-exp-kesht',{roleTitle:'مهندس زیرساخت و پلتفرم',organizationName:'هلدینگ کشت',employmentType:'FULL_TIME',location:'تهران، ایران',startDate:date(1405,4),isCurrent:true,summary:'راه‌اندازی و مدیریت سرویس‌های داخلی و زیرساخت خودمیزبان.',responsibilities:['مدیریت GitLab، Nexus و ابزارهای همکاری تیمی','خودکارسازی ماشین‌های مجازی با Ansible و VMware','طراحی زیرساخت Kubernetes، پایش و مدیریت هویت'],technologies:['Kubernetes','Ansible','VMware','GitLab','Nexus'],skillIds:['demo-skill-0','demo-skill-4']}),
   item('demo-exp-ekyc',{roleTitle:'توسعه‌دهنده و مهندس DevOps',organizationName:'پروژهٔ TseTab | احراز هویت الکترونیکی',summary:'مشارکت در توسعه و زیرساخت سرویس احراز هویت با بیش از دو میلیون کاربر.',responsibilities:['توسعه و ارتقای سرویس‌های Angular و .NET','پیاده‌سازی استقرار، پایش و تست خودکار'],technologies:['Angular','.NET','SQL Server','Docker','Kubernetes','Azure DevOps']})
  ],
  projects:[
   item('demo-project-hatef',{title:'موتور جستجو و پروفایل حرفه‌ای هاتف',projectType:'PERSONAL',subtitle:'زیرساخت جستجو و هویت حرفه‌ای فارسی',description:'توسعهٔ موتور جستجو و صفحهٔ حرفه‌ای فارسی با ویرایشگر راست‌به‌چپ و پیش‌نمایش زنده.',role:'طراحی و توسعه',organization:'Hatef',isOngoing:true,problem:'نیاز به حضور حرفه‌ای و جستجوی بومی با پشتیبانی مناسب از زبان فارسی.',solution:'طراحی سرویس‌های جستجو و پروفایل با API نسخه‌دار و فرم‌های ساخت‌یافته.',architecture:'C++، MongoDB، Redis و رابط وب واکنش‌گرا',outcomes:['پروفایل حرفه‌ای با سوابق، مهارت‌ها و پروژه‌ها','ذخیره‌سازی خودکار و مدیریت حریم خصوصی'],technologies:['C++','MongoDB','Redis','JavaScript','Docker'],links:[{title:'کد منبع',url:'https://github.com/hatefsystems/search-engine-core'}],skillIds:['demo-skill-1','demo-skill-4']}),
   item('demo-project-cloud',{title:'زیرساخت ابری و استقرار خودکار',projectType:'PROFESSIONAL',description:'راه‌اندازی سرویس‌های کانتینری و خطوط استقرار برای تیم‌های محصول.',role:'DevOps و طراحی زیرساخت',organization:'QuickHands Inc.',problem:'نیاز به استقرار تکرارپذیر و پایش یکپارچهٔ سرویس‌ها.',solution:'استفاده از ECS Fargate، زیرساخت به‌صورت کد و CI/CD.',technologies:['AWS','Fargate','CloudFormation','GitHub Actions'],experienceIds:['demo-exp-quickhands'],skillIds:['demo-skill-2']})
  ],
  certifications:['AWS Certified Cloud Practitioner','AWS Certified AI Practitioner','AWS Certified Solutions Architect – Associate'].map((name,i)=>item('demo-cert-'+i,{name,issuingOrganization:'Amazon Web Services',skillIds:['demo-skill-2']})),
  education:[item('demo-learning',{kind:'SELF_LEARNING',institutionName:'یادگیری مستمر در مهندسی پلتفرم',description:'مطالعه و تمرین عملی در معماری ابری، Kubernetes و اتوماسیون. این مورد جایگزین مدرک تحصیلی نیست.'})],
  openSource:[item('demo-opensource',{platform:'GitHub',repositoryName:'hatefsystems/search-engine-core',repositoryUrl:'https://github.com/hatefsystems/search-engine-core',contributionType:'توسعه و نگهداری',role:'توسعه‌دهنده',description:'توسعهٔ موتور جستجو و پروفایل حرفه‌ای هاتف.',technologies:['C++','JavaScript','Docker']})],
  services:[item('demo-service',{title:'مشاورهٔ DevOps و زیرساخت ابری',description:'طراحی CI/CD، کانتینرسازی، پایش و بهینه‌سازی زیرساخت برای تیم‌های محصول.',category:'مهندسی پلتفرم',deliveryMode:'REMOTE',pricingMode:'CONTACT',availability:'با هماهنگی',contactMethod:'از طریق صفحهٔ حرفه‌ای',skillIds:['demo-skill-0','demo-skill-1','demo-skill-2'],projectIds:['demo-project-cloud']})],
  achievements:[item('demo-achievement',{type:'پروژه',title:'مشارکت در سامانهٔ احراز هویت با بیش از دو میلیون کاربر',issuer:'پروژهٔ TseTab',description:'تجربهٔ توسعه و عملیات سرویس احراز هویت الکترونیکی در مقیاس سازمانی.'})],
  languages:[item('demo-language-fa',{name:'فارسی',proficiency:'NATIVE'}),item('demo-language-en',{name:'انگلیسی',proficiency:'CONVERSATIONAL'})],
  contacts:[item('demo-contact',{type:'LINK',label:'مخزن پروژهٔ هاتف',value:'https://github.com/hatefsystems/search-engine-core'})],
  availability:[item('demo-availability',{type:'CONSULTING',status:'AVAILABLE',description:'گفتگو دربارهٔ طراحی پلتفرم، DevOps و زیرساخت ابری.'})],
  about:[item('demo-about',{title:'مسیر حرفه‌ای من',description:'از توسعهٔ نرم‌افزار تا طراحی زیرساخت و مهندسی پلتفرم. تمرکز من روی اتوماسیون، قابلیت اطمینان و ساخت محصول است.'})],
  publications:[item('demo-publication',{title:'نمونهٔ آزمایشی مقالهٔ مهندسی پلتفرم',type:'ARTICLE',description:'این رکورد فقط برای بررسی فرم مقاله ساخته شده و سابقهٔ واقعی انتشار نیست.',visibility:'HIDDEN'})],
  recommendations:[item('demo-recommendation',{authorName:'نویسندهٔ آزمایشی',authorTitle:'نمونه برای بررسی رابط',relationship:'نمونهٔ آزمایشی',content:'این متن فقط برای تست فرم توصیه‌نامه است و توصیهٔ واقعی شخص دیگری نیست.',sourceUrl:'https://example.com/demo-only',visibility:'HIDDEN'})]
 },
 links:[{title:'GitHub هاتف',url:'https://github.com/hatefsystems/search-engine-core',description:'کد منبع پروژه',visibility:'PUBLIC',privacy:'PUBLIC',isActive:true,sortOrder:0}]
};
