# syntax=docker/dockerfile:1
ARG UBUNTU_IMAGE
FROM ${UBUNTU_IMAGE}
ARG MONGO_C_VERSION
ARG MONGO_CXX_VERSION
ARG BUILD_JOBS=2
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates wget build-essential cmake git pkg-config \
    libssl-dev zlib1g-dev libuv1-dev nlohmann-json3-dev && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /tmp/mongodb
RUN wget -q "https://github.com/mongodb/mongo-c-driver/releases/download/${MONGO_C_VERSION}/mongo-c-driver-${MONGO_C_VERSION}.tar.gz" && \
    tar xzf "mongo-c-driver-${MONGO_C_VERSION}.tar.gz" && \
    cmake -S "mongo-c-driver-${MONGO_C_VERSION}" -B c-build \
        -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DCMAKE_INSTALL_LIBDIR=lib -DENABLE_TESTS=OFF && \
    cmake --build c-build --parallel "${BUILD_JOBS}" && \
    cmake --install c-build && rm -rf ./*
RUN wget -q "https://github.com/mongodb/mongo-cxx-driver/releases/download/r${MONGO_CXX_VERSION}/mongo-cxx-driver-r${MONGO_CXX_VERSION}.tar.gz" && \
    tar xzf "mongo-cxx-driver-r${MONGO_CXX_VERSION}.tar.gz" && \
    cmake -S "mongo-cxx-driver-r${MONGO_CXX_VERSION}" -B cxx-build \
        -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_PREFIX_PATH=/usr/local \
        -DBSONCXX_POLY_USE_BOOST=0 -DCMAKE_CXX_STANDARD=20 -DBUILD_TESTING=OFF && \
    cmake --build cxx-build --parallel "${BUILD_JOBS}" && \
    cmake --install cxx-build && ldconfig && rm -rf ./*
WORKDIR /app
