name: API Documentation Validation

on:
  push:
    paths:
      - 'docs/api/**'
      - 'package.json'
      - '.prettierrc.json'
      - 'scripts/validate-schema.js'
  pull_request:
    paths:
      - 'docs/api/**'
      - 'package.json'
      - '.prettierrc.json'
      - 'scripts/validate-schema.js'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check formatting with Prettier
      run: npm run format:check
      
    - name: Validate JSON examples against schema
      run: npm run validate-schema
      
    - name: Verify API documentation files exist
      run: |
        echo "Checking required API documentation files..."
        test -f docs/api/search_endpoint.md || (echo "❌ Missing docs/api/search_endpoint.md" && exit 1)
        test -f docs/api/search_response.schema.json || (echo "❌ Missing docs/api/search_response.schema.json" && exit 1)
        echo "✅ All required files exist" 