name: 🚀 CI/CD Pipeline

on:
  push:
    branches: [ master ]
    paths:
      - '**'
  pull_request:
    branches: [ master ]
    paths:
      - '**'
  workflow_dispatch:
    inputs:
      cache_version:
        description: 'Cache version (change this to bust Docker cache)'
        required: false
        default: '1'
        type: string

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  docker-build:
    uses: ./.github/workflows/docker-build-orchestrator.yml
    with:
      cache_version: ${{ inputs.cache_version || '1' }}