name: Docker Build Pipeline

on:
  workflow_call:
    inputs:
      docker_image:
        required: false
        type: string
      docker_tag:
        required: false
        type: string
      cache_version:
        required: false
        type: string
        default: '1'

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  build-drivers:
    uses: ./.github/workflows/docker-build-drivers.yml
    with:
      docker_image: ghcr.io/${{ github.repository }}/mongodb-drivers
      docker_tag: latest

  build-server:
    needs: build-drivers
    uses: ./.github/workflows/docker-build-server.yml
    with:
      docker_image: ghcr.io/${{ github.repository }}/mongodb-server
      docker_tag: latest

  build-app:
    needs: build-server
    uses: ./.github/workflows/docker-build-app.yml
    with:
      docker_image: ghcr.io/${{ github.repository }}
      docker_tag: latest
      cache_version: ${{ inputs.cache_version }}

